version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: hawkstack-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hawkstack
      MYSQL_USER: hawkstack
      MYSQL_PASSWORD: hawkstack123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
